import AsyncStorage from '@react-native-async-storage/async-storage';
import { User, Post, ProfessionalProfile, ClientProfile, Review, Conversation, Message } from './types';

// Sample professionals - expanded with more categories
const sampleProfessionals: ProfessionalProfile[] = [
  {
    id: 'pro-1',
    email: 'mike.johnson@email.com',
    role: 'professional',
    name: 'Mike Johnson',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    city: 'Los Angeles',
    createdAt: '2024-01-15T10:00:00Z',
    trade: 'Master Electrician',
    serviceCategories: ['electrical', 'smart-home', 'handyman'],
    yearsExperience: 12,
    licenseNumber: 'CA-ELE-123456',
    serviceArea: ['Los Angeles', 'Santa Monica', 'Pasadena', 'Burbank'],
    description:
      'Licensed master electrician with over 12 years of experience. Specializing in residential rewiring, panel upgrades, and smart home installations. Available for emergency calls.',
    rating: 4.9,
    reviewCount: 127,
  },
  {
    id: 'pro-2',
    email: 'sarah.green@email.com',
    role: 'professional',
    name: 'Sarah Green',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    city: 'San Francisco',
    createdAt: '2024-02-20T14:30:00Z',
    trade: 'Landscape Designer',
    serviceCategories: ['landscaping', 'lawn-care', 'irrigation'],
    yearsExperience: 8,
    serviceArea: ['San Francisco', 'Oakland', 'Berkeley', 'Marin'],
    description:
      'Creating beautiful outdoor spaces that blend functionality with aesthetics. Sustainable design practices and native plant expertise. Award-winning designs.',
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 'pro-3',
    email: 'david.chen@email.com',
    role: 'professional',
    name: 'David Chen',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    city: 'Seattle',
    createdAt: '2024-01-08T09:15:00Z',
    trade: 'Professional Cleaner',
    serviceCategories: ['house-cleaning', 'deep-cleaning', 'carpet-cleaning'],
    yearsExperience: 5,
    serviceArea: ['Seattle', 'Bellevue', 'Redmond', 'Kirkland'],
    description:
      'Eco-friendly deep cleaning services for homes and offices. We use only non-toxic, environmentally safe products. Satisfaction guaranteed.',
    rating: 4.7,
    reviewCount: 203,
  },
  {
    id: 'pro-4',
    email: 'amanda.martinez@email.com',
    role: 'professional',
    name: 'Amanda Martinez',
    photoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200',
    city: 'Denver',
    createdAt: '2024-03-01T11:45:00Z',
    trade: 'Licensed Plumber',
    serviceCategories: ['plumbing', 'bathroom-remodel', 'handyman'],
    yearsExperience: 15,
    licenseNumber: 'CO-PLB-789012',
    serviceArea: ['Denver', 'Aurora', 'Lakewood', 'Littleton'],
    description:
      'Full-service plumbing for residential and commercial properties. Bathroom remodels a specialty. Emergency services available 24/7.',
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: 'pro-5',
    email: 'james.wilson@email.com',
    role: 'professional',
    name: 'James Wilson',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    city: 'Los Angeles',
    createdAt: '2023-11-10T08:00:00Z',
    trade: 'General Contractor',
    serviceCategories: ['handyman', 'carpentry', 'painting', 'drywall'],
    yearsExperience: 20,
    licenseNumber: 'CA-GC-456789',
    serviceArea: ['Los Angeles', 'Hollywood', 'Beverly Hills', 'West Hollywood'],
    description:
      'Jack of all trades, master of many. From small repairs to full renovations, I bring 20 years of craftsmanship to every project.',
    rating: 4.8,
    reviewCount: 312,
  },
  {
    id: 'pro-6',
    email: 'lisa.thompson@email.com',
    role: 'professional',
    name: 'Lisa Thompson',
    photoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    city: 'Austin',
    createdAt: '2024-01-20T15:30:00Z',
    trade: 'Interior Painter',
    serviceCategories: ['painting', 'drywall'],
    yearsExperience: 10,
    serviceArea: ['Austin', 'Round Rock', 'Cedar Park', 'Georgetown'],
    description:
      'Transforming homes one room at a time. Specializing in color consultation, faux finishes, and cabinet refinishing. Clean, efficient work.',
    rating: 4.9,
    reviewCount: 178,
  },
  {
    id: 'pro-7',
    email: 'carlos.rodriguez@email.com',
    role: 'professional',
    name: 'Carlos Rodriguez',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
    city: 'Miami',
    createdAt: '2023-09-05T12:00:00Z',
    trade: 'HVAC Technician',
    serviceCategories: ['hvac', 'appliance-repair'],
    yearsExperience: 14,
    licenseNumber: 'FL-HVAC-234567',
    serviceArea: ['Miami', 'Fort Lauderdale', 'Coral Gables', 'Miami Beach'],
    description:
      'Keep your cool in Florida heat! Expert AC installation, repair, and maintenance. Same-day service available.',
    rating: 4.7,
    reviewCount: 245,
  },
  {
    id: 'pro-8',
    email: 'jennifer.park@email.com',
    role: 'professional',
    name: 'Jennifer Park',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
    city: 'Seattle',
    createdAt: '2024-02-01T10:00:00Z',
    trade: 'Professional Organizer',
    serviceCategories: ['junk-removal', 'moving', 'packing', 'storage'],
    yearsExperience: 6,
    serviceArea: ['Seattle', 'Tacoma', 'Bellevue', 'Everett'],
    description:
      'Life-changing organization and decluttering services. From closets to whole-home transformations. Moving and packing services too!',
    rating: 5.0,
    reviewCount: 67,
  },
  {
    id: 'pro-9',
    email: 'marcus.brown@email.com',
    role: 'professional',
    name: 'Marcus Brown',
    photoUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=200',
    city: 'Chicago',
    createdAt: '2023-06-15T14:00:00Z',
    trade: 'Flooring Specialist',
    serviceCategories: ['flooring', 'tiling', 'carpentry'],
    yearsExperience: 18,
    serviceArea: ['Chicago', 'Evanston', 'Oak Park', 'Naperville'],
    description:
      'Expert flooring installation - hardwood, laminate, vinyl, and tile. Family business with three generations of craftsmanship.',
    rating: 4.9,
    reviewCount: 289,
  },
  {
    id: 'pro-10',
    email: 'rachel.kim@email.com',
    role: 'professional',
    name: 'Rachel Kim',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
    city: 'San Francisco',
    createdAt: '2024-03-10T09:00:00Z',
    trade: 'Pet Care Specialist',
    serviceCategories: ['dog-sitting', 'pet-grooming', 'house-sitting'],
    yearsExperience: 7,
    serviceArea: ['San Francisco', 'Daly City', 'South San Francisco'],
    description:
      'Your pets deserve the best! Professional pet sitting, grooming, and overnight care. Vet tech certified with lots of love to give.',
    rating: 5.0,
    reviewCount: 134,
  },
  {
    id: 'pro-11',
    email: 'tom.baker@email.com',
    role: 'professional',
    name: 'Tom Baker',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200',
    city: 'Denver',
    createdAt: '2023-12-01T11:00:00Z',
    trade: 'Roofer',
    serviceCategories: ['roofing', 'gutters', 'siding'],
    yearsExperience: 22,
    licenseNumber: 'CO-ROOF-111222',
    serviceArea: ['Denver', 'Boulder', 'Fort Collins', 'Colorado Springs'],
    description:
      'Keeping Colorado homes protected for over 20 years. Expert in all roofing types, storm damage repair, and gutter installation.',
    rating: 4.8,
    reviewCount: 198,
  },
  {
    id: 'pro-12',
    email: 'nina.patel@email.com',
    role: 'professional',
    name: 'Nina Patel',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200',
    city: 'Austin',
    createdAt: '2024-01-05T16:00:00Z',
    trade: 'Home Organizer',
    serviceCategories: ['house-cleaning', 'personal-assistant'],
    yearsExperience: 4,
    serviceArea: ['Austin', 'San Marcos', 'New Braunfels'],
    description:
      'From chaos to calm! Professional home organization and personal assistance. Specializing in busy families and home offices.',
    rating: 4.9,
    reviewCount: 45,
  },
];

// Sample clients - expanded
const sampleClients: ClientProfile[] = [
  {
    id: 'client-1',
    email: 'john.doe@email.com',
    role: 'client',
    name: 'John Doe',
    photoUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=200',
    city: 'Los Angeles',
    neighborhood: 'Silver Lake',
    feedRadius: 20,
    rating: 4.8,
    reviewCount: 12,
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'client-2',
    email: 'emily.wilson@email.com',
    role: 'client',
    name: 'Emily Wilson',
    photoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200',
    city: 'San Francisco',
    neighborhood: 'Mission District',
    feedRadius: 20,
    rating: 5.0,
    reviewCount: 8,
    createdAt: '2024-02-15T16:30:00Z',
  },
  {
    id: 'client-3',
    email: 'robert.taylor@email.com',
    role: 'client',
    name: 'Robert Taylor',
    photoUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200',
    city: 'Seattle',
    neighborhood: 'Capitol Hill',
    feedRadius: 20,
    rating: 4.5,
    reviewCount: 6,
    createdAt: '2024-03-10T12:00:00Z',
  },
  {
    id: 'client-4',
    email: 'maria.garcia@email.com',
    role: 'client',
    name: 'Maria Garcia',
    photoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200',
    city: 'Denver',
    neighborhood: 'Cherry Creek',
    feedRadius: 20,
    rating: 4.9,
    reviewCount: 15,
    createdAt: '2024-01-25T09:00:00Z',
  },
  {
    id: 'client-5',
    email: 'kevin.lee@email.com',
    role: 'client',
    name: 'Kevin Lee',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200',
    city: 'Austin',
    neighborhood: 'East Austin',
    feedRadius: 20,
    rating: 4.7,
    reviewCount: 9,
    createdAt: '2024-03-05T14:00:00Z',
  },
  {
    id: 'client-6',
    email: 'susan.moore@email.com',
    role: 'client',
    name: 'Susan Moore',
    photoUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200',
    city: 'Chicago',
    neighborhood: 'Lincoln Park',
    feedRadius: 20,
    rating: 4.6,
    reviewCount: 11,
    createdAt: '2024-02-20T11:00:00Z',
  },
  {
    id: 'client-7',
    email: 'daniel.white@email.com',
    role: 'client',
    name: 'Daniel White',
    photoUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=200',
    city: 'Miami',
    neighborhood: 'Wynwood',
    feedRadius: 20,
    rating: 4.4,
    reviewCount: 5,
    createdAt: '2024-01-10T15:00:00Z',
  },
];

// Sample posts - expanded
const samplePosts: Post[] = [
  {
    id: 'post-1',
    authorId: 'pro-1',
    authorName: 'Mike Johnson',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Complete electrical panel upgrade',
    description:
      'Just finished upgrading a 100-amp panel to 200-amp for a growing family. Added dedicated circuits for EV charger and home office. Clean install with proper labeling.',
    images: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    ],
    serviceCategoryId: 'electrical',
    serviceCategoryName: 'Electrical',
    city: 'Los Angeles',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 24,
    dislikes: 1,
  },
  {
    id: 'post-2',
    authorId: 'client-1',
    authorName: 'John Doe',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=200',
    authorRole: 'client',
    type: 'job_done',
    title: 'Amazing backyard transformation',
    description:
      'Sarah Green did an incredible job transforming our neglected backyard into a beautiful garden oasis. Highly recommend her landscape design services!',
    images: [
      'https://images.unsplash.com/photo-1558904541-efa843a96f01?w=800',
      'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800',
    ],
    serviceCategoryId: 'landscaping',
    serviceCategoryName: 'Landscaping',
    city: 'San Francisco',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 45,
    dislikes: 0,
  },
  {
    id: 'post-3',
    authorId: 'pro-2',
    authorName: 'Sarah Green',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Drought-resistant front yard',
    description:
      'Converted a thirsty lawn into a stunning drought-resistant landscape. Native California plants, decorative gravel, and drip irrigation. Water bill cut by 60%!',
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
    serviceCategoryId: 'landscaping',
    serviceCategoryName: 'Landscaping',
    city: 'San Francisco',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    likes: 67,
    dislikes: 2,
  },
  {
    id: 'post-4',
    authorId: 'client-2',
    authorName: 'Emily Wilson',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200',
    authorRole: 'client',
    type: 'job_done',
    title: 'Deep clean made my home feel new',
    description:
      'Had David Chen\'s team do a deep clean before our baby arrived. Every corner was spotless and they used all eco-friendly products. Peace of mind for our growing family.',
    images: [
      'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800',
    ],
    serviceCategoryId: 'house-cleaning',
    serviceCategoryName: 'House Cleaning',
    city: 'Seattle',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    likes: 32,
    dislikes: 0,
  },
  {
    id: 'post-5',
    authorId: 'pro-4',
    authorName: 'Amanda Martinez',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Emergency water heater replacement',
    description:
      'Replaced a failed 40-gallon water heater with a new high-efficiency tankless unit. Family had hot water same day. Always prepared for emergencies!',
    images: [
      'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800',
    ],
    serviceCategoryId: 'plumbing',
    serviceCategoryName: 'Plumbing',
    city: 'Denver',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    likes: 28,
    dislikes: 1,
  },
  {
    id: 'post-6',
    authorId: 'pro-3',
    authorName: 'David Chen',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Move-out deep cleaning complete',
    description:
      'Completed a comprehensive move-out cleaning for a 3-bedroom apartment. All deposits secured for our client. Includes carpet steam cleaning and window washing.',
    images: [
      'https://images.unsplash.com/photo-1527515545081-5db817172677?w=800',
    ],
    serviceCategoryId: 'house-cleaning',
    serviceCategoryName: 'House Cleaning',
    city: 'Seattle',
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    likes: 19,
    dislikes: 0,
  },
  {
    id: 'post-7',
    authorId: 'pro-5',
    authorName: 'James Wilson',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Custom built-in bookshelf installation',
    description:
      'Designed and built a floor-to-ceiling bookshelf with integrated lighting. Solid oak with a natural finish. Client wanted a library feel - mission accomplished!',
    images: [
      'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=800',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    ],
    serviceCategoryId: 'carpentry',
    serviceCategoryName: 'Carpentry',
    city: 'Los Angeles',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    likes: 89,
    dislikes: 0,
  },
  {
    id: 'post-8',
    authorId: 'client-4',
    authorName: 'Maria Garcia',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200',
    authorRole: 'client',
    type: 'job_done',
    title: 'Bathroom remodel turned out perfect',
    description:
      'Amanda Martinez and her team completely transformed our master bathroom. New fixtures, tiling, and a walk-in shower. Stayed on budget and finished early!',
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800',
    ],
    serviceCategoryId: 'bathroom-remodel',
    serviceCategoryName: 'Bathroom Remodel',
    city: 'Denver',
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    likes: 56,
    dislikes: 1,
  },
  {
    id: 'post-9',
    authorId: 'pro-6',
    authorName: 'Lisa Thompson',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Kitchen cabinet refresh',
    description:
      'Gave these dated oak cabinets a modern update with a two-tone paint job. Soft gray on the lowers, bright white on the uppers. New hardware really makes it pop!',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
    ],
    serviceCategoryId: 'painting',
    serviceCategoryName: 'Painting',
    city: 'Austin',
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    likes: 73,
    dislikes: 2,
  },
  {
    id: 'post-10',
    authorId: 'pro-7',
    authorName: 'Carlos Rodriguez',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'New AC system installation',
    description:
      'Installed a brand new 5-ton Carrier system with smart thermostat integration. This Miami home will stay cool all summer. Energy efficient and whisper quiet!',
    images: [
      'https://images.unsplash.com/photo-1631545806609-737931dded48?w=800',
    ],
    serviceCategoryId: 'hvac',
    serviceCategoryName: 'HVAC',
    city: 'Miami',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    likes: 34,
    dislikes: 0,
  },
  {
    id: 'post-11',
    authorId: 'client-5',
    authorName: 'Kevin Lee',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200',
    authorRole: 'client',
    type: 'job_done',
    title: 'Whole house painted in 3 days',
    description:
      'Lisa Thompson and her crew painted our entire 2,500 sq ft home interior in just 3 days. The attention to detail and color matching was incredible. Looks brand new!',
    images: [
      'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800',
    ],
    serviceCategoryId: 'painting',
    serviceCategoryName: 'Painting',
    city: 'Austin',
    createdAt: new Date(Date.now() - 40 * 60 * 60 * 1000).toISOString(),
    likes: 41,
    dislikes: 0,
  },
  {
    id: 'post-12',
    authorId: 'pro-9',
    authorName: 'Marcus Brown',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Hardwood floor restoration',
    description:
      'Brought these 50-year-old oak floors back to life. Sanded, stained, and finished with 3 coats of water-based poly. The grain really pops now!',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      'https://images.unsplash.com/photo-1617104678098-de229db51175?w=800',
    ],
    serviceCategoryId: 'flooring',
    serviceCategoryName: 'Flooring',
    city: 'Chicago',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: 92,
    dislikes: 1,
  },
  {
    id: 'post-13',
    authorId: 'client-6',
    authorName: 'Susan Moore',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200',
    authorRole: 'client',
    type: 'job_done',
    title: 'New hardwood throughout main floor',
    description:
      'Marcus Brown installed beautiful hickory hardwood in our living room, dining room, and kitchen. The craftsmanship is outstanding. Worth every penny!',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ],
    serviceCategoryId: 'flooring',
    serviceCategoryName: 'Flooring',
    city: 'Chicago',
    createdAt: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    likes: 38,
    dislikes: 0,
  },
  {
    id: 'post-14',
    authorId: 'pro-10',
    authorName: 'Rachel Kim',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Week-long pet sitting for 3 dogs',
    description:
      'Had the best time caring for Max, Bella, and Charlie while their family was on vacation. Daily walks, lots of playtime, and plenty of cuddles. They were such good pups!',
    images: [
      'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
      'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800',
    ],
    serviceCategoryId: 'dog-sitting',
    serviceCategoryName: 'Pet Sitting',
    city: 'San Francisco',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    likes: 156,
    dislikes: 0,
  },
  {
    id: 'post-15',
    authorId: 'pro-11',
    authorName: 'Tom Baker',
    authorPhotoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200',
    authorRole: 'professional',
    type: 'completed_work',
    title: 'Storm damage roof repair',
    description:
      'Fixed hail damage on this beautiful home after last week\'s storm. Replaced damaged shingles, checked for leaks, and cleaned all gutters. Good as new!',
    images: [
      'https://images.unsplash.com/photo-1632759145351-1d592919f522?w=800',
    ],
    serviceCategoryId: 'roofing',
    serviceCategoryName: 'Roofing',
    city: 'Denver',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    likes: 27,
    dislikes: 0,
  },
];

// Sample reviews
const sampleReviews: Review[] = [
  {
    id: 'review-1',
    professionalId: 'pro-1',
    clientId: 'client-1',
    clientName: 'John Doe',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=200',
    rating: 5,
    description: 'Mike did an outstanding job upgrading our electrical panel. He was professional, explained everything clearly, and left the work area spotless. Highly recommend!',
    media: [],
    serviceCategoryId: 'electrical',
    serviceCategoryName: 'Electrical',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-2',
    professionalId: 'pro-2',
    clientId: 'client-2',
    clientName: 'Emily Wilson',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200',
    rating: 5,
    description: 'Sarah transformed our backyard into a paradise! Her design sense is incredible and she really listened to what we wanted. The native plants she chose are thriving.',
    media: [],
    serviceCategoryId: 'landscaping',
    serviceCategoryName: 'Landscaping',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-3',
    professionalId: 'pro-4',
    clientId: 'client-4',
    clientName: 'Maria Garcia',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=200',
    rating: 5,
    description: 'Amanda and her team were amazing! Our bathroom remodel was completed on time and under budget. The quality of work is exceptional. We\'re already planning our kitchen remodel with her.',
    media: [],
    serviceCategoryId: 'bathroom-remodel',
    serviceCategoryName: 'Bathroom Remodel',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-4',
    professionalId: 'pro-3',
    clientId: 'client-3',
    clientName: 'Robert Taylor',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200',
    rating: 4,
    description: 'David\'s cleaning service is thorough and they use great eco-friendly products. Only reason for 4 stars is they were 30 minutes late, but the work itself was excellent.',
    media: [],
    serviceCategoryId: 'house-cleaning',
    serviceCategoryName: 'House Cleaning',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-5',
    professionalId: 'pro-6',
    clientId: 'client-5',
    clientName: 'Kevin Lee',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200',
    rating: 5,
    description: 'Lisa is a true artist! The color consultation alone was worth it. She helped us pick the perfect palette and the execution was flawless. Our home feels completely refreshed.',
    media: [],
    serviceCategoryId: 'painting',
    serviceCategoryName: 'Painting',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'review-6',
    professionalId: 'pro-9',
    clientId: 'client-6',
    clientName: 'Susan Moore',
    clientPhotoUrl: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=200',
    rating: 5,
    description: 'Marcus is a true craftsman. He restored our original hardwood floors and they look better than new. His attention to detail is remarkable. Will definitely use him again!',
    media: [],
    serviceCategoryId: 'flooring',
    serviceCategoryName: 'Flooring',
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Sample conversations
const sampleConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: ['client-1', 'pro-1'],
    participantNames: ['John Doe', 'Mike Johnson'],
    participantPhotos: [
      'https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=200',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    ],
    participantRoles: ['client', 'professional'],
    lastMessage: 'Thanks Mike! The panel upgrade looks great.',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
  },
  {
    id: 'conv-2',
    participants: ['client-2', 'pro-2'],
    participantNames: ['Emily Wilson', 'Sarah Green'],
    participantPhotos: [
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    ],
    participantRoles: ['client', 'professional'],
    lastMessage: 'The plants are settling in beautifully!',
    lastMessageAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
  },
];

// Sample messages
const sampleMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'client-1',
    receiverId: 'pro-1',
    content: 'Hi Mike, I saw your post about the panel upgrade. We need the same work done at our house.',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'pro-1',
    receiverId: 'client-1',
    content: 'Hi John! I\'d be happy to help. What\'s your current panel amperage and what are you looking to add?',
    createdAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'client-1',
    receiverId: 'pro-1',
    content: 'We have 100 amps now. We want to add an EV charger and maybe a hot tub eventually.',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'pro-1',
    receiverId: 'client-1',
    content: 'Perfect, you\'ll definitely want to upgrade to 200 amps. I can come by tomorrow for a free estimate if that works?',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-5',
    conversationId: 'conv-1',
    senderId: 'client-1',
    receiverId: 'pro-1',
    content: 'Thanks Mike! The panel upgrade looks great.',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-6',
    conversationId: 'conv-2',
    senderId: 'client-2',
    receiverId: 'pro-2',
    content: 'Sarah, the backyard is absolutely stunning! Thank you so much.',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-7',
    conversationId: 'conv-2',
    senderId: 'pro-2',
    receiverId: 'client-2',
    content: 'I\'m so glad you love it! Remember to water the new plantings every other day for the first month.',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: 'msg-8',
    conversationId: 'conv-2',
    senderId: 'client-2',
    receiverId: 'pro-2',
    content: 'The plants are settling in beautifully!',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
];

export async function seedSampleData(): Promise<void> {
  // Check if we already have data
  const existingUsers = await AsyncStorage.getItem('registered-users');
  const existingPosts = await AsyncStorage.getItem('posts-storage');
  const existingReviews = await AsyncStorage.getItem('reviews-storage');
  const existingMessages = await AsyncStorage.getItem('messages-storage');

  // Only seed if no users exist yet
  if (!existingUsers) {
    const allUsers: User[] = [...sampleProfessionals, ...sampleClients];
    await AsyncStorage.setItem('registered-users', JSON.stringify(allUsers));
    console.log('Seeded sample users');
  }

  // Only seed posts if storage doesn't exist
  if (!existingPosts) {
    const postsStorage = {
      state: {
        posts: samplePosts,
        reactions: [],
        filters: {
          type: 'all',
          categoryId: undefined,
          city: undefined,
        },
      },
      version: 0,
    };
    await AsyncStorage.setItem('posts-storage', JSON.stringify(postsStorage));
    console.log('Seeded sample posts');
  }

  // Seed reviews
  if (!existingReviews) {
    const reviewsStorage = {
      state: {
        reviews: sampleReviews,
      },
      version: 0,
    };
    await AsyncStorage.setItem('reviews-storage', JSON.stringify(reviewsStorage));
    console.log('Seeded sample reviews');
  }

  // Seed messages
  if (!existingMessages) {
    const messagesStorage = {
      state: {
        conversations: sampleConversations,
        messages: sampleMessages,
      },
      version: 0,
    };
    await AsyncStorage.setItem('messages-storage', JSON.stringify(messagesStorage));
    console.log('Seeded sample messages');
  }
}

export async function clearAllData(): Promise<void> {
  await AsyncStorage.multiRemove([
    'registered-users',
    'auth-storage',
    'posts-storage',
    'messages-storage',
    'reviews-storage',
    'reports-storage',
    'professionals-storage',
  ]);
  console.log('Cleared all data');
}
